### ISSUE TITLE
impyla only works with thrift-0.9.3

### ISSUE THREAD

**Issue by czxm** [cloudera/impyla#234]
I observed some python environment installed thrift-0.10 by default, which breaks impyla with below error:

impala/_thrift_gen/TCLIService/TCLIService.py", line 1109, in read
    fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
AttributeError: 'TSaslClientTransport' object has no attribute 'trans'

Usually I can fix this issue by enforcing thrift-0.9.3:
pip install thrift=0.9.3

Can we have this in the README?

**Comment by wesm** [comment]
The proper fix is to make https://github.com/cloudera/thrift_sasl work with Thrift 0.10. Want to take a shot?

**Comment by jiajie1999** [comment]
+1 
Have same problem, But working good on python3.4 with same code

```
 select * from nginx_log limit 10
Traceback (most recent call last):
  File "util.py", line 72, in <module>
    print(extract(" select * from nginx_log limit 10"))
  File "util.py", line 16, in extract
    cur = conn.cursor()
  File "/usr/local/lib/python2.7/site-packages/impala/hiveserver2.py", line 125, in cursor
    session = self.service.open_session(user, configuration)
  File "/usr/local/lib/python2.7/site-packages/impala/hiveserver2.py", line 995, in open_session
    resp = self._rpc('OpenSession', req)
  File "/usr/local/lib/python2.7/site-packages/impala/hiveserver2.py", line 923, in _rpc
    response = self._execute(func_name, request)
  File "/usr/local/lib/python2.7/site-packages/impala/hiveserver2.py", line 940, in _execute
    return func(request)
  File "/usr/local/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 175, in OpenSession
    return self.recv_OpenSession()
  File "/usr/local/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 193, in recv_OpenSession
    result.read(self._iprot)
  File "/usr/local/lib/python2.7/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 1109, in read
    fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
AttributeError: 'TSaslClientTransport' object has no attribute 'trans'
```

**Comment by mariusvniekerk** [comment]
you probably also need to rebuild the generated thrift bindings.  thrift 0.10 has made some api changes :(

**Comment by git4impatient** [comment]
The thrift 9.3 didn't work on CentOS7.3  this works with Thrift 10

git clone https://github.com/cloudera/thrift_sasl
python setup.py build
python setup.py install
pip install sasl
pip install impyla
pip install  thrift
pip show thrift

python...
from impala.dbapi import connect
conn = connect(host='yourhost', port=21050)
cursor = conn.cursor()
cursor.execute('SELECT * FROM yourtable LIMIT 10')
print cursor.description  # prints the result set's schema
results = cursor.fetchall()
print results

**Comment by gregory-dan** [comment]
thrift-0.10.0
thrift_sasl-0.2.1
sasl-0.2.1
impyla-0.14.0

RedHat 7.3 and Python 2.7

Still does not work for me with the same error:

  File "./hive_cleanup.py", line 89, in __init__
    self.cursor = hive.cursor()
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/hiveserver2.py", line 125, in cursor
    session = self.service.open_session(user, configuration)
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/hiveserver2.py", line 995, in open_session
    resp = self._rpc('OpenSession', req)
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/hiveserver2.py", line 923, in _rpc
    response = self._execute(func_name, request)
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/hiveserver2.py", line 940, in _execute
    return func(request)
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/_thrift_gen/TCLIService/TCLIService.py", line 175, in OpenSession
    return self.recv_OpenSession()
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/_thrift_gen/TCLIService/TCLIService.py", line 193, in recv_OpenSession
    result.read(self._iprot)
  File "/home/jenkins/workspace/Environment/Datalake/hive-cleanup/impala/_thrift_gen/TCLIService/TCLIService.py", line 1109, in read
    fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
AttributeError: 'TSaslClientTransport' object has no attribute 'trans'

**Comment by lfyzjck** [comment]
Temporary you can fork this project and recompile thrift idl with thrift 0.10.0.

install thrift-compiler=0.10.0, go to the project root:

```
thrift -gen py -out ./ impala/thrift/TCLIService.thrift
```

This just work fine to me. I had published the package to internal mirror.

**Comment by venkatsambath** [comment]
https://community.cloudera.com/t5/Interactive-Short-cycle-SQL/Python-Error-TSaslClientTransport-object-has-no-attribute-trans/td-p/58033 -- has the fix

**Comment by csringhofer** [comment]
Closing this as the issue is out of date (currently Impyla used Thrift 0.16.0)
