### ISSUE TITLE
'TSocket' object has no attribute 'isOpen'

### ISSUE THREAD

**Issue by tdhopper** [cloudera/impyla#268]
I'm seeing this error for the first time:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-b8033d8b7753> in <module>()
      1 impala.dbapi.connect(host=HOST, port=PORT, auth_mechanism='PLAIN',
----> 2                     user=USER, password=PASSWORD)

~/miniconda2/envs/env/lib/python3.6/site-packages/impala/dbapi.py in connect(host, port, database, timeout, use_ssl, ca_cert, auth_mechanism, user, password, kerberos_service_name, use_ldap, ldap_user, ldap_password, use_kerberos, protocol)
    145                           ca_cert=ca_cert, user=user, password=password,
    146                           kerberos_service_name=kerberos_service_name,
--> 147                           auth_mechanism=auth_mechanism)
    148     return hs2.HiveServer2Connection(service, default_db=database)
    149 

~/miniconda2/envs/env/lib/python3.6/site-packages/impala/hiveserver2.py in connect(host, port, timeout, use_ssl, ca_cert, user, password, kerberos_service_name, auth_mechanism)
    756     transport = get_transport(sock, host, kerberos_service_name,
    757                               auth_mechanism, user, password)
--> 758     transport.open()
    759     protocol = TBinaryProtocol(transport)
    760     if six.PY2:

~/miniconda2/envs/env/lib/python3.6/site-packages/thrift_sasl/__init__.py in open(self)
     65 
     66   def open(self):
---> 67     if not self._trans.isOpen():
     68       self._trans.open()
     69 

AttributeError: 'TSocket' object has no attribute 'isOpen'
```

These are versions I have installed:

```
thrift==0.9.3
thrift-sasl==0.3.0
thriftpy==0.3.9
impyla==0.14.0
```

**Comment by wesm** [comment]
I just pushed thrift_sasl 0.3.0 yesterday so it must be a version incompatibility. Can you upgrade to thrift 0.10.0? We probably need a version bump in impyla to pin things properly

**Comment by tdhopper** [comment]
@wesm Thanks. I actually get the same error with 0.10.0.

**Comment by wesm** [comment]
OK, will the fix is to pin thrift_sasl at 0.2.1 until we get impyla working on 0.10.0 + thrift_sasl 0.3.0. I am unable to work on it today unfortunately =/

**Comment by tdhopper** [comment]
Yup, that works.

**Comment by rockot** [comment]
Hello!
I can't solve this problem with "AttributeError: 'TSocket' object has no attribute 'isOpen'" even with thrift_sasl == 0.2.1 installated...may be some other libraries should be exact versions? If so, what libraries and their versions should i check?
I use anaconda by the way.
Thanks!

**Comment by tdhopper** [comment]
@rockot Maybe try `thrift=0.9.3`

**Comment by rockot** [comment]
yes, this works, thanks! and also, suddenly,  i needed sasl==0.2.1

**Comment by igorivanov** [comment]
Hello!
I create PR - https://github.com/cloudera/thrift_sasl/pull/10 - in a thrift_sasl module. It fix compatibility erors.

**Comment by rsadaphule** [comment]
I attempted to install pip install git+https://github.com/cloudera/thrift_sasl and ran into TSocket thrift_sas1 error. I checked version . It says sasl-0.2.1 thrift-sasl-0.3.0.

Could someone send me exact command to pin to 0.2.1

**Comment by qp910** [comment]
hlpe me, （if thrift_sasl=0.3.0,it will AttributeError: 'TSocket' object has no attribute 'isOpen'.but, thrift_sasl=0.2.1,it will thriftpy.transport.TTransportException: TTransportException(type=1, message="Could not start SASL: b'Error in sasl_client_start (-4) SASL(-4): no mechanism available: Unable to find a callback: 2'")
supplement
）

**Comment by xiaomaosusie** [comment]
Hi Guys, 

I"m having:
thrift==0.11.0
thrift-sasl==0.3.0
thriftpy==0.3.9
impyla==0.14.1

and I"m getting ''TSSLSocket' object has no attribute 'isOpen'' . Is it also bc of version issues? Shall I downgrade any of them? 

Thank you so much for your help! Much appreciated! 

Best,
Susie

**Comment by catchcharan** [comment]
Hi guys,

I'm able to resolve this issue with a workaround and little tweaking.

I uninstalled thrift_sasl on my anaconda3 environment. Then copied then directory from anaconda2 directory to anaconda3 directory. This change worked.

cd /opt/anaconda2/lib/python2.7/site-packages/
cp -R thrift_sasl /opt/anaconda3/lib/python3.6/site-packages/

Thanks,
Meher

**Comment by merritth** [comment]
I am experiencing the same issue with TSocket object has no attribute isOpen.

thrift-sasl 0.3.0
sasl 0.2.1
impyla 0.14.1

I'd love to be able to connect to a hive server via python...

**Comment by yerra** [comment]
I am using Anaconda 3  Environment  with python 3.6.4 .Even I am getting  'TSocket' object has not attribute 'isOpen'  issue. 
But I am unable to downgrade thrift_sasl below 0.3.0  Any Idea why I am uable to downgrade ?

thrift = 0.11.0
thrift-sasl 0.3.0
thrift-py=0.3.9
impyla 0.14.1

**Comment by merritth** [comment]
> Make sure to Restart your kernel if you're working in a Jupyter notebook!
> 
> I had the same problem connecting to Hive even after pip installing thrift_sasl==0.2.1, and was reminded by IT to restart my kernel before the changes take effect.

Do you mean restart your Hive kernel or the kernel within your notebook?

**Comment by yerra** [comment]
I am using Anaconda  Snyder . I did restart kernel restart at Ipython console  . How to do Hive Kernel restart ?

**Comment by merritth** [comment]
That would be on your IT department I believe. I am not familiar how to reboot a hive/hadoop kernel.

**Comment by yerra** [comment]
I am running this on  VM  , Which I can do my self if it resolves the issue. I will try and update

**Comment by RobertFeyerharm** [comment]
@merritth Restart the kernel within your notebook. On the notebook toolbar: Kernel -> Restart

**Comment by 416381012** [comment]
I hava resolved it by use 0.2.1 version

**Comment by Kxrr** [comment]
The dependencies below **work for me** on ubuntu docker container to initialize hive and impala client both.

# requirements.txt

```
impyla==0.15.0
sasl==0.2.1
thrift_sasl==0.2.1
thriftpy==0.3.9
thriftpy2==0.4.0
```

# apt packages
`sudo apt-get install libsasl2-dev libsasl2-2 libsasl2-modules-gssapi-mit`

**Comment by be-rock** [comment]
bitarray                  1.0.1            py37h7b6447c_0
ca-certificates           2019.10.16                    0
cyrus-sasl                2.1.26               h82bf5a1_4
impyla                    0.15.0                   py37_0
krb5                      1.16.1               h173b8e3_7
ncurses                   6.1                  he6710b0_1
openssl                   1.1.1d               h7b6447c_3
python                    3.7.4                h265db76_1
sasl                      0.2.1            py37h779454e_1
six                       1.12.0                   py37_0
thrift                    0.11.0           py37hf484d3e_0
thrift_sasl               0.3.0                    py37_1
thriftpy                  0.3.9            py37h14c3975_2
thriftpy2                 0.4.7            py37h516909a_0

```
from impala.dbapi import connect
conn = connect(host='host', port=21050, auth_mechanism='GSSAPI', use_ssl=True, timeout=10, ca_cert='/path/to/pemfile.pem', kerberos_service_name='impala')
AttributeError: 'TSSLSocket' object has no attribute 'isOpen'
```

I dont have the option to downgrade to `thrift_sasl==0.2.1` as it would force a downgrade to the version of python in my environment.

**Comment by canada11** [comment]
Had the same problem. If you follow the error around, for me at least, the problem is that thrift-sasl calls isOpen() on a TSocket object (which exists in thriftpy2), but that object only has a function called is_open().

Looking at thrift-sasl, this was actually fixed in version 0.4.0 that was released on Dec. 13, 2019.

So make sure your package manager of choice is pulling thrift-sasl 0.4.0 and it should be fixed

**Comment by timarmstrong** [comment]
@dknupp do we plan to make the 0.4.0 release of thrift-sasl non-alpha?

**Comment by MacwinWin** [comment]
**pandas.read_sql()** still not working under **thrift-sasl-0.4.2** but **thrift-sasl-0.2.1** works fine

**Comment by Kingflyinger** [comment]
> **pandas.read_sql()** still not working under **thrift-sasl-0.4.2** but **thrift-sasl-0.2.1** works fine

same,it occured the same problem with thrift-sasl >0.4.0
thrift                             0.13.0
thrift-sasl                        0.4.2
thriftpy                           0.3.9
thriftpy2                          0.4.14

**Comment by Kingflyinger** [comment]
> Had the same problem. If you follow the error around, for me at least, the problem is that thrift-sasl calls isOpen() on a TSocket object (which exists in thriftpy2), but that object only has a function called is_open().
> 
> Looking at thrift-sasl, this was actually fixed in version 0.4.0 that was released on Dec. 13, 2019.
> 
> So make sure your package manager of choice is pulling thrift-sasl >= 0.4.0 and it should be fixed.
> pypi at https://pypi.org/project/thrift-sasl/#history shows that thrift-sasl (as of Jan. 23, 2020) only has version 3 being distributed, so most are probably using pip and only getting version 3. Until pypi is updated with version 0.4.0, then the new version can be obtained with `pip install thrift-sasl==0.4a1`
it occured the same question
thrift                             0.13.0
thrift-sasl                        0.4.2
thriftpy                           0.3.9
thriftpy2                          0.4.14
