### ISSUE TITLE
TypeError: can't concat bytes to str (Python 3.5, thrift-sasl with pure-sasl)

### ISSUE THREAD

**Issue by ha62791** [cloudera/impyla#238]
Due to issue #237 ,
I uninstalled sasl 0.2.1 and replaced it with pure-sasl 0.3.0
based on below commit by @nonsleepr :
[https://github.com/cloudera/impyla/commit/5e386d6495b580ae88efd81dd0f8927af5157bb8](url)

but then I got below error:
```
>>> conn = connect(host='<host>', port=21050, database='<db>', auth_mechanism='PLAIN', user='<user>', password='<pass>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/python/miniconda3/lib/python3.5/site-packages/impala/dbapi.py", line 147, in connect
    auth_mechanism=auth_mechanism)
  File "/tmp/python/miniconda3/lib/python3.5/site-packages/impala/hiveserver2.py", line 758, in connect
    transport.open()
  File "/tmp/python/miniconda3/lib/python3.5/site-packages/thrift_sasl-0.2.1-py3.5.egg/thrift_sasl/__init__.py", line 75, in open
  File "/tmp/python/miniconda3/lib/python3.5/site-packages/thrift_sasl-0.2.1-py3.5.egg/thrift_sasl/__init__.py", line 94, in _send_message
TypeError: can't concat bytes to str
```

I am using:
- CDH 5.8 / 5.9
- Anaconda Python 3.5
- impyla 0.14.0
- bitarray 0.8.1
- thriftpy 0.3.9
- six 1.10.0
- thrift-sasl 0.2.1
- **pure-sasl 0.3.0**

**Comment by ha62791** [comment]
This problem does not exist in Python 2.7

**Comment by ha62791** [comment]
By changing line 94 in `thrift_sasl/__init__.py`
to
```
print('Type of header:' + str(type(header)))
print('Type of body:' + str(type(body)))
self._trans.write(header + body.encode())
```
The output shows that on the first time `_send_message` is called it `body` is passed as str.
The second time it is passed correctly as bytes
```
Type of header:<class 'bytes'>
Type of body:<class 'str'>
Type of header:<class 'bytes'>
Type of body:<class 'bytes'>
```

Here's a fix for the problem
After installing:
- thrift-sasl 0.2.1 (installed via pip with '--no-deps' option)
- pure-sasl 0.3.0

Go to directory `<site-packages path>\thrift_sasl`
Remove `__pycache__` if exists
Append below codes before line 94 `self._trans.write(header + body)` in `__init__.py`:
```
    if (type(body) is str):
      body = body.encode()
```

**Comment by qp910** [comment]
@ha62791 I do it,but it will AttributeError: 'TSocket' object has no attribute 'readAll'

**Comment by amirmazmi** [comment]
I have the same issue, and the workaround results in the same AttributeError.

**Comment by nonsleepr** [comment]
This `pure-sasl` bug was fixed in thobbs/pure-sasl#21. Updating the lib should help.

**Comment by Jonnyczh** [comment]
I used this work around but I am still getting this error. TSocket' object has no attribute 'readAll'. It seems to originate from thrift's "class TTransportBase(object):" specifically.

I am using,

- impyla==0.14.1
- thrift==0.11.0
- thrift-sasl==0.3.0

**Comment by U201315019** [comment]
I have the same issue, and the workaround results in the same AttributeError.Have you solved this problem？ @Jonnyczh

**Comment by Jonnyczh** [comment]
Hi @U201315019, sorry, I have not found a fix for this yet.

**Comment by scottInTempe** [comment]
I'm having same issue here.

**Comment by albertaz** [comment]
Hello, I have the same TSocket' object has no attribute 'readAll' error too. 
I am using python 3.5.2 on Linux (Ubuntu).
I have installed sasl wrapper using sudo apt install libsasl2-dev as per the reference below:
https://stackoverflow.com/questions/22838752/hadoop-python-client-driver-for-hiveserver2-fails-to-install

My package versions are:

impyla==0.14.1
thriftpy==0.3.9
thrift==0.11.0
thrift-sasl==0.3.0
sasl==0.2.1
pure-sasl==0.5.1

Please Help!

**Comment by parthb102** [comment]
Was anyone able to find a fix?

**Comment by apollos** [comment]
seems it can only work with python2.7

**Comment by yanirs** [comment]
> This `pure-sasl` bug was fixed in [thobbs/pure-sasl#21](https://github.com/thobbs/pure-sasl/issues/21). Updating the lib should help.

@nonsleepr This doesn't seem to be a `pure-sasl` issue, as it's still a problem with 0.6.1.

As @ha62791 noted, the problem appears to be in `thrift-sasl`. There's an open issue and PR for it: https://github.com/cloudera/thrift_sasl/issues/14 and https://github.com/cloudera/thrift_sasl/pull/17.

Unfortunately, it looks like no one has the time to merge the PR or implement a better fix, so the best solution may be to fork `thrift-sasl` and make the changes to your copy.

**Comment by yanirs** [comment]
> Unfortunately, it looks like no one has the time to merge the PR or implement a better fix

Looking at this repo's recent history, it seems like @dknupp has the capacity to help. Any chance of this and other issues getting more attention? I'm happy to help with pushing this stuff forward, as we rely heavily on impyla at my company.

**Comment by fat8701** [comment]
```
modify thrift_sasl\__init__.py
...
  def _send_message(self, status, body):
    header = struct.pack(">BI", status, len(body))
------
#add code
    if (type(body) is str):
      body = body.encode()
------
    self._trans.write(header + body)
    self._trans.flush()
```

**Comment by timarmstrong** [comment]
I merged the PR for thrift_sasl. I guess we need to do a release for thrift_sasl next

**Comment by dknupp** [comment]
Sadly, the cloudera/thrift_sasl#17 appears to introduce a regression for python 2. See:
https://github.com/cloudera/thrift_sasl/issues/18

I think `bytearrray()` might be the preferred fix, rather than `str.encode()`.
